/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ffmpegdemo_VideoUtils */

#ifndef _Included_com_ffmpegdemo_VideoUtils
#define _Included_com_ffmpegdemo_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ffmpegdemo_VideoUtils
 * Method:    Decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ffmpegdemo_VideoUtils_Decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
